name: Build and Deploy
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: yarn install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: yarn build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Deploy 🚀
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version.
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: 'dist'

          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: Emma Lawson

          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_email: emma@vdhinc.org

          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Commit from GitHub Actions Deploy'
